
name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    env:
      MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
      MONDAY_BOARD_ID: ${{ secrets.MONDAY_BOARD_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.25"
          python-version: ${{ matrix.python-version }}

      - name: Sync
        run: uv sync

      - name: Run tests
        run: uv run pytest
