
name: CI

on: [push, pull_request]

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.25"
          python-version: ${{ matrix.python-version }}

      - name: Sync
        run: uv sync

      - name: Import library
        # This checks if we're triggering any syntax errors in older Python versions
        run: python -c "import mondantic"
